name: Qodana Code Quality Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - 'releases/*'
  push:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: ${{ github.event_name == 'pull_request' }}
          upload-result: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_129550057 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
