name: Qodana Code Quality Analysis

on:
  workflow_run:
    workflows: ["CI/CD Pipeline YpareoLike"]
    types:
      - completed
  workflow_dispatch:

jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write

    steps:
      - name: Checkout code from the successful build
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: ${{ github.event.workflow_run.event == 'pull_request' }}
          upload-result: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_129550057 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
